<?php

declare(strict_types=1);

namespace Nexara\ApiPlatformVoter\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

final class Configuration implements ConfigurationInterface
{
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('nexara_api_platform_voter');

        $treeBuilder->getRootNode()
            ->children()
            ->booleanNode('enabled')
            ->info('Enable/disable the voter bundle globally')
            ->defaultTrue()
            ->end()
            ->booleanNode('enforce_collection_list')
            ->info('Enforce authorization checks for collection list operations')
            ->defaultTrue()
            ->end()
            ->booleanNode('strict_mode')
            ->info('Throw exception if no voter supports the attribute (instead of denying silently)')
            ->defaultFalse()
            ->end()
            ->booleanNode('debug')
            ->info('Enable debug mode with detailed authorization decision logging')
            ->defaultFalse()
            ->end()
            ->enumNode('debug_output')
            ->info('Debug output format')
            ->values(['simple', 'detailed', 'json'])
            ->defaultValue('detailed')
            ->end()
            ->integerNode('cache_ttl')
            ->info('Cache TTL in seconds for metadata resolution (0 to disable)')
            ->defaultValue(3600)
            ->min(0)
            ->end()
            ->enumNode('cache_warming_strategy')
            ->info('Cache warming strategy')
            ->values(['eager', 'lazy', 'on_demand'])
            ->defaultValue('eager')
            ->end()
            ->enumNode('error_reporting_level')
            ->info('Error reporting level for authorization failures')
            ->values(['silent', 'minimal', 'detailed', 'verbose'])
            ->defaultValue('detailed')
            ->end()
            ->arrayNode('audit')
            ->addDefaultsIfNotSet()
            ->children()
            ->booleanNode('enabled')
            ->info('Enable audit logging for authorization decisions')
            ->defaultFalse()
            ->end()
            ->enumNode('logger')
            ->info('Audit logger type')
            ->values(['database', 'file', 'monolog', 'custom'])
            ->defaultValue('monolog')
            ->end()
            ->enumNode('level')
            ->info('What to log')
            ->values(['all', 'denied_only', 'granted_only'])
            ->defaultValue('all')
            ->end()
            ->booleanNode('include_context')
            ->info('Include request context in audit logs')
            ->defaultTrue()
            ->end()
            ->integerNode('retention_days')
            ->info('Number of days to retain audit logs')
            ->defaultValue(90)
            ->min(1)
            ->end()
            ->end()
            ->end()
            ->arrayNode('rate_limiting')
            ->addDefaultsIfNotSet()
            ->children()
            ->booleanNode('enabled')
            ->info('Enable rate limiting for authorization checks')
            ->defaultFalse()
            ->end()
            ->integerNode('max_attempts')
            ->info('Maximum authorization attempts per window')
            ->defaultValue(100)
            ->min(1)
            ->end()
            ->integerNode('window')
            ->info('Time window in seconds')
            ->defaultValue(60)
            ->min(1)
            ->end()
            ->enumNode('strategy')
            ->info('Rate limiting strategy')
            ->values(['fixed_window', 'sliding_window', 'token_bucket'])
            ->defaultValue('sliding_window')
            ->end()
            ->end()
            ->end()
            ->arrayNode('performance')
            ->addDefaultsIfNotSet()
            ->children()
            ->booleanNode('enable_memoization')
            ->info('Enable within-request result memoization')
            ->defaultTrue()
            ->end()
            ->booleanNode('enable_reflection_cache')
            ->info('Enable reflection caching')
            ->defaultTrue()
            ->end()
            ->booleanNode('lazy_voter_loading')
            ->info('Enable lazy loading of voters')
            ->defaultFalse()
            ->end()
            ->integerNode('voter_timeout')
            ->info('Maximum time in seconds for voter decision (0 = no timeout)')
            ->defaultValue(0)
            ->min(0)
            ->end()
            ->end()
            ->end()
            ->arrayNode('context')
            ->addDefaultsIfNotSet()
            ->children()
            ->booleanNode('enabled')
            ->info('Enable context-aware authorization')
            ->defaultTrue()
            ->end()
            ->booleanNode('include_ip')
            ->info('Include IP address in context')
            ->defaultTrue()
            ->end()
            ->booleanNode('include_user_agent')
            ->info('Include user agent in context')
            ->defaultTrue()
            ->end()
            ->booleanNode('include_time')
            ->info('Include request time in context')
            ->defaultTrue()
            ->end()
            ->end()
            ->end()
            ->end();

        return $treeBuilder;
    }
}
