name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please describe it below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: I would like to be able to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?
      placeholder: I've tried...

  - type: textarea
    id: example
    attributes:
      label: Example Usage
      description: Show how the feature would be used
      render: php
      placeholder: |
        #[ApiResourceVoter(
            voter: ArticleVoter::class,
            newFeature: true
        )]

  - type: checkboxes
    id: breaking
    attributes:
      label: Breaking Change
      description: Would this be a breaking change?
      options:
        - label: This would be a breaking change
        - label: This is backward compatible

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context or screenshots
